/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ALambdaFuncName extends PFuncName
{
    private TLambdaStart _lambdaStart_;

    public ALambdaFuncName()
    {
        // Constructor
    }

    public ALambdaFuncName(
        @SuppressWarnings("hiding") TLambdaStart _lambdaStart_)
    {
        // Constructor
        setLambdaStart(_lambdaStart_);

    }

    @Override
    public Object clone()
    {
        return new ALambdaFuncName(
            cloneNode(this._lambdaStart_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALambdaFuncName(this);
    }

    public TLambdaStart getLambdaStart()
    {
        return this._lambdaStart_;
    }

    public void setLambdaStart(TLambdaStart node)
    {
        if(this._lambdaStart_ != null)
        {
            this._lambdaStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lambdaStart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lambdaStart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lambdaStart_ == child)
        {
            this._lambdaStart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lambdaStart_ == oldChild)
        {
            setLambdaStart((TLambdaStart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
