/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ATEscapeChar extends PEscapeChar
{
    private TEscapeTab _escapeTab_;

    public ATEscapeChar()
    {
        // Constructor
    }

    public ATEscapeChar(
        @SuppressWarnings("hiding") TEscapeTab _escapeTab_)
    {
        // Constructor
        setEscapeTab(_escapeTab_);

    }

    @Override
    public Object clone()
    {
        return new ATEscapeChar(
            cloneNode(this._escapeTab_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATEscapeChar(this);
    }

    public TEscapeTab getEscapeTab()
    {
        return this._escapeTab_;
    }

    public void setEscapeTab(TEscapeTab node)
    {
        if(this._escapeTab_ != null)
        {
            this._escapeTab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeTab_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeTab_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeTab_ == child)
        {
            this._escapeTab_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeTab_ == oldChild)
        {
            setEscapeTab((TEscapeTab) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
