/* This file was generated by SableCC (http://www.sablecc.org/). */

package three_point_one.node;

import three_point_one.analysis.*;

@SuppressWarnings("nls")
public final class ACompoundS extends PS
{
    private PS _s_;
    private TSemi _semi_;
    private PC _c_;

    public ACompoundS()
    {
        // Constructor
    }

    public ACompoundS(
        @SuppressWarnings("hiding") PS _s_,
        @SuppressWarnings("hiding") TSemi _semi_,
        @SuppressWarnings("hiding") PC _c_)
    {
        // Constructor
        setS(_s_);

        setSemi(_semi_);

        setC(_c_);

    }

    @Override
    public Object clone()
    {
        return new ACompoundS(
            cloneNode(this._s_),
            cloneNode(this._semi_),
            cloneNode(this._c_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompoundS(this);
    }

    public PS getS()
    {
        return this._s_;
    }

    public void setS(PS node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    public PC getC()
    {
        return this._c_;
    }

    public void setC(PC node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._s_)
            + toString(this._semi_)
            + toString(this._c_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._s_ == oldChild)
        {
            setS((PS) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        if(this._c_ == oldChild)
        {
            setC((PC) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
