/* This file was generated by SableCC (http://www.sablecc.org/). */

package three_point_one.node;

import three_point_one.analysis.*;

@SuppressWarnings("nls")
public final class APrintS extends PS
{
    private PPrintStmt _printStmt_;

    public APrintS()
    {
        // Constructor
    }

    public APrintS(
        @SuppressWarnings("hiding") PPrintStmt _printStmt_)
    {
        // Constructor
        setPrintStmt(_printStmt_);

    }

    @Override
    public Object clone()
    {
        return new APrintS(
            cloneNode(this._printStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrintS(this);
    }

    public PPrintStmt getPrintStmt()
    {
        return this._printStmt_;
    }

    public void setPrintStmt(PPrintStmt node)
    {
        if(this._printStmt_ != null)
        {
            this._printStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._printStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._printStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._printStmt_ == child)
        {
            this._printStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._printStmt_ == oldChild)
        {
            setPrintStmt((PPrintStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
