/* This file was generated by SableCC (http://www.sablecc.org/). */

package three_point_one.node;

import three_point_one.analysis.*;

@SuppressWarnings("nls")
public final class ACompoundS extends PS
{
    private PS _first_;
    private TSemi _semi_;
    private PS _second_;

    public ACompoundS()
    {
        // Constructor
    }

    public ACompoundS(
        @SuppressWarnings("hiding") PS _first_,
        @SuppressWarnings("hiding") TSemi _semi_,
        @SuppressWarnings("hiding") PS _second_)
    {
        // Constructor
        setFirst(_first_);

        setSemi(_semi_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ACompoundS(
            cloneNode(this._first_),
            cloneNode(this._semi_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompoundS(this);
    }

    public PS getFirst()
    {
        return this._first_;
    }

    public void setFirst(PS node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    public PS getSecond()
    {
        return this._second_;
    }

    public void setSecond(PS node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._semi_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PS) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
