/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class TLambdaStart extends Token
{
    public TLambdaStart()
    {
        super.setText("\\");
    }

    public TLambdaStart(int line, int pos)
    {
        super.setText("\\");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLambdaStart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLambdaStart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLambdaStart text.");
    }
}
