/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AEqualNativeBinOp extends PNativeBinOp
{
    private TEqual _equal_;

    public AEqualNativeBinOp()
    {
        // Constructor
    }

    public AEqualNativeBinOp(
        @SuppressWarnings("hiding") TEqual _equal_)
    {
        // Constructor
        setEqual(_equal_);

    }

    @Override
    public Object clone()
    {
        return new AEqualNativeBinOp(
            cloneNode(this._equal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualNativeBinOp(this);
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
