/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultEscapeChar extends PEscapeChar
{
    private TEscapeDefault _escapeDefault_;

    public ADefaultEscapeChar()
    {
        // Constructor
    }

    public ADefaultEscapeChar(
        @SuppressWarnings("hiding") TEscapeDefault _escapeDefault_)
    {
        // Constructor
        setEscapeDefault(_escapeDefault_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultEscapeChar(
            cloneNode(this._escapeDefault_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultEscapeChar(this);
    }

    public TEscapeDefault getEscapeDefault()
    {
        return this._escapeDefault_;
    }

    public void setEscapeDefault(TEscapeDefault node)
    {
        if(this._escapeDefault_ != null)
        {
            this._escapeDefault_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeDefault_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeDefault_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeDefault_ == child)
        {
            this._escapeDefault_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeDefault_ == oldChild)
        {
            setEscapeDefault((TEscapeDefault) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
