/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AHeadNativeUnaryOp extends PNativeUnaryOp
{
    private THead _head_;

    public AHeadNativeUnaryOp()
    {
        // Constructor
    }

    public AHeadNativeUnaryOp(
        @SuppressWarnings("hiding") THead _head_)
    {
        // Constructor
        setHead(_head_);

    }

    @Override
    public Object clone()
    {
        return new AHeadNativeUnaryOp(
            cloneNode(this._head_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHeadNativeUnaryOp(this);
    }

    public THead getHead()
    {
        return this._head_;
    }

    public void setHead(THead node)
    {
        if(this._head_ != null)
        {
            this._head_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._head_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._head_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._head_ == child)
        {
            this._head_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._head_ == oldChild)
        {
            setHead((THead) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
