/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AHexEscapeChar extends PEscapeChar
{
    private TEscapeHexChar _escapeHexChar_;

    public AHexEscapeChar()
    {
        // Constructor
    }

    public AHexEscapeChar(
        @SuppressWarnings("hiding") TEscapeHexChar _escapeHexChar_)
    {
        // Constructor
        setEscapeHexChar(_escapeHexChar_);

    }

    @Override
    public Object clone()
    {
        return new AHexEscapeChar(
            cloneNode(this._escapeHexChar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHexEscapeChar(this);
    }

    public TEscapeHexChar getEscapeHexChar()
    {
        return this._escapeHexChar_;
    }

    public void setEscapeHexChar(TEscapeHexChar node)
    {
        if(this._escapeHexChar_ != null)
        {
            this._escapeHexChar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeHexChar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeHexChar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeHexChar_ == child)
        {
            this._escapeHexChar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeHexChar_ == oldChild)
        {
            setEscapeHexChar((TEscapeHexChar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
