/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ALengthNativeUnaryOp extends PNativeUnaryOp
{
    private TLength _length_;

    public ALengthNativeUnaryOp()
    {
        // Constructor
    }

    public ALengthNativeUnaryOp(
        @SuppressWarnings("hiding") TLength _length_)
    {
        // Constructor
        setLength(_length_);

    }

    @Override
    public Object clone()
    {
        return new ALengthNativeUnaryOp(
            cloneNode(this._length_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALengthNativeUnaryOp(this);
    }

    public TLength getLength()
    {
        return this._length_;
    }

    public void setLength(TLength node)
    {
        if(this._length_ != null)
        {
            this._length_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._length_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._length_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._length_ == child)
        {
            this._length_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._length_ == oldChild)
        {
            setLength((TLength) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
