/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AMoreBodyStringMiddle extends PStringMiddle
{
    private PStringMiddle _stringMiddle_;
    private TStringBody _stringBody_;

    public AMoreBodyStringMiddle()
    {
        // Constructor
    }

    public AMoreBodyStringMiddle(
        @SuppressWarnings("hiding") PStringMiddle _stringMiddle_,
        @SuppressWarnings("hiding") TStringBody _stringBody_)
    {
        // Constructor
        setStringMiddle(_stringMiddle_);

        setStringBody(_stringBody_);

    }

    @Override
    public Object clone()
    {
        return new AMoreBodyStringMiddle(
            cloneNode(this._stringMiddle_),
            cloneNode(this._stringBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreBodyStringMiddle(this);
    }

    public PStringMiddle getStringMiddle()
    {
        return this._stringMiddle_;
    }

    public void setStringMiddle(PStringMiddle node)
    {
        if(this._stringMiddle_ != null)
        {
            this._stringMiddle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringMiddle_ = node;
    }

    public TStringBody getStringBody()
    {
        return this._stringBody_;
    }

    public void setStringBody(TStringBody node)
    {
        if(this._stringBody_ != null)
        {
            this._stringBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringMiddle_)
            + toString(this._stringBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringMiddle_ == child)
        {
            this._stringMiddle_ = null;
            return;
        }

        if(this._stringBody_ == child)
        {
            this._stringBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringMiddle_ == oldChild)
        {
            setStringMiddle((PStringMiddle) newChild);
            return;
        }

        if(this._stringBody_ == oldChild)
        {
            setStringBody((TStringBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
