/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AReverseNativeUnaryOp extends PNativeUnaryOp
{
    private TReverse _reverse_;

    public AReverseNativeUnaryOp()
    {
        // Constructor
    }

    public AReverseNativeUnaryOp(
        @SuppressWarnings("hiding") TReverse _reverse_)
    {
        // Constructor
        setReverse(_reverse_);

    }

    @Override
    public Object clone()
    {
        return new AReverseNativeUnaryOp(
            cloneNode(this._reverse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReverseNativeUnaryOp(this);
    }

    public TReverse getReverse()
    {
        return this._reverse_;
    }

    public void setReverse(TReverse node)
    {
        if(this._reverse_ != null)
        {
            this._reverse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reverse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reverse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reverse_ == child)
        {
            this._reverse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reverse_ == oldChild)
        {
            setReverse((TReverse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
