/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AStringString extends PString
{
    private TStringStart _stringStart_;
    private PStringMiddle _stringMiddle_;
    private TStringEnd _stringEnd_;

    public AStringString()
    {
        // Constructor
    }

    public AStringString(
        @SuppressWarnings("hiding") TStringStart _stringStart_,
        @SuppressWarnings("hiding") PStringMiddle _stringMiddle_,
        @SuppressWarnings("hiding") TStringEnd _stringEnd_)
    {
        // Constructor
        setStringStart(_stringStart_);

        setStringMiddle(_stringMiddle_);

        setStringEnd(_stringEnd_);

    }

    @Override
    public Object clone()
    {
        return new AStringString(
            cloneNode(this._stringStart_),
            cloneNode(this._stringMiddle_),
            cloneNode(this._stringEnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringString(this);
    }

    public TStringStart getStringStart()
    {
        return this._stringStart_;
    }

    public void setStringStart(TStringStart node)
    {
        if(this._stringStart_ != null)
        {
            this._stringStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringStart_ = node;
    }

    public PStringMiddle getStringMiddle()
    {
        return this._stringMiddle_;
    }

    public void setStringMiddle(PStringMiddle node)
    {
        if(this._stringMiddle_ != null)
        {
            this._stringMiddle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringMiddle_ = node;
    }

    public TStringEnd getStringEnd()
    {
        return this._stringEnd_;
    }

    public void setStringEnd(TStringEnd node)
    {
        if(this._stringEnd_ != null)
        {
            this._stringEnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringEnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringStart_)
            + toString(this._stringMiddle_)
            + toString(this._stringEnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringStart_ == child)
        {
            this._stringStart_ = null;
            return;
        }

        if(this._stringMiddle_ == child)
        {
            this._stringMiddle_ = null;
            return;
        }

        if(this._stringEnd_ == child)
        {
            this._stringEnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringStart_ == oldChild)
        {
            setStringStart((TStringStart) newChild);
            return;
        }

        if(this._stringMiddle_ == oldChild)
        {
            setStringMiddle((PStringMiddle) newChild);
            return;
        }

        if(this._stringEnd_ == oldChild)
        {
            setStringEnd((TStringEnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
