/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AUnicodeEscapeChar extends PEscapeChar
{
    private TEscapeUnicodeChar _escapeUnicodeChar_;

    public AUnicodeEscapeChar()
    {
        // Constructor
    }

    public AUnicodeEscapeChar(
        @SuppressWarnings("hiding") TEscapeUnicodeChar _escapeUnicodeChar_)
    {
        // Constructor
        setEscapeUnicodeChar(_escapeUnicodeChar_);

    }

    @Override
    public Object clone()
    {
        return new AUnicodeEscapeChar(
            cloneNode(this._escapeUnicodeChar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicodeEscapeChar(this);
    }

    public TEscapeUnicodeChar getEscapeUnicodeChar()
    {
        return this._escapeUnicodeChar_;
    }

    public void setEscapeUnicodeChar(TEscapeUnicodeChar node)
    {
        if(this._escapeUnicodeChar_ != null)
        {
            this._escapeUnicodeChar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeUnicodeChar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeUnicodeChar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeUnicodeChar_ == child)
        {
            this._escapeUnicodeChar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeUnicodeChar_ == oldChild)
        {
            setEscapeUnicodeChar((TEscapeUnicodeChar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
