/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.parser;

import wolf.node.*;
import wolf.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTStringStart(@SuppressWarnings("unused") TStringStart node)
    {
        this.index = 0;
    }

    @Override
    public void caseTStringEscape(@SuppressWarnings("unused") TStringEscape node)
    {
        this.index = 1;
    }

    @Override
    public void caseTEscapeAlarm(@SuppressWarnings("unused") TEscapeAlarm node)
    {
        this.index = 2;
    }

    @Override
    public void caseTEscapeBackspace(@SuppressWarnings("unused") TEscapeBackspace node)
    {
        this.index = 3;
    }

    @Override
    public void caseTEscapeFormfeed(@SuppressWarnings("unused") TEscapeFormfeed node)
    {
        this.index = 4;
    }

    @Override
    public void caseTEscapeCarriageReturn(@SuppressWarnings("unused") TEscapeCarriageReturn node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEscapeNewline(@SuppressWarnings("unused") TEscapeNewline node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEscapeTab(@SuppressWarnings("unused") TEscapeTab node)
    {
        this.index = 7;
    }

    @Override
    public void caseTEscapeVerticalTab(@SuppressWarnings("unused") TEscapeVerticalTab node)
    {
        this.index = 8;
    }

    @Override
    public void caseTEscapeBackslash(@SuppressWarnings("unused") TEscapeBackslash node)
    {
        this.index = 9;
    }

    @Override
    public void caseTEscapeSingleQuote(@SuppressWarnings("unused") TEscapeSingleQuote node)
    {
        this.index = 10;
    }

    @Override
    public void caseTEscapeDoubleQuote(@SuppressWarnings("unused") TEscapeDoubleQuote node)
    {
        this.index = 11;
    }

    @Override
    public void caseTEscapeQuestionMark(@SuppressWarnings("unused") TEscapeQuestionMark node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEscapeOctalChar(@SuppressWarnings("unused") TEscapeOctalChar node)
    {
        this.index = 13;
    }

    @Override
    public void caseTEscapeHexChar(@SuppressWarnings("unused") TEscapeHexChar node)
    {
        this.index = 14;
    }

    @Override
    public void caseTEscapeUnicodeChar(@SuppressWarnings("unused") TEscapeUnicodeChar node)
    {
        this.index = 15;
    }

    @Override
    public void caseTEscapeDefault(@SuppressWarnings("unused") TEscapeDefault node)
    {
        this.index = 16;
    }

    @Override
    public void caseTStringBody(@SuppressWarnings("unused") TStringBody node)
    {
        this.index = 17;
    }

    @Override
    public void caseTStringEnd(@SuppressWarnings("unused") TStringEnd node)
    {
        this.index = 18;
    }

    @Override
    public void caseTHead(@SuppressWarnings("unused") THead node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTail(@SuppressWarnings("unused") TTail node)
    {
        this.index = 20;
    }

    @Override
    public void caseTReverse(@SuppressWarnings("unused") TReverse node)
    {
        this.index = 21;
    }

    @Override
    public void caseTAppend(@SuppressWarnings("unused") TAppend node)
    {
        this.index = 22;
    }

    @Override
    public void caseTPrepend(@SuppressWarnings("unused") TPrepend node)
    {
        this.index = 23;
    }

    @Override
    public void caseTFoldl(@SuppressWarnings("unused") TFoldl node)
    {
        this.index = 24;
    }

    @Override
    public void caseTFoldr(@SuppressWarnings("unused") TFoldr node)
    {
        this.index = 25;
    }

    @Override
    public void caseTMap(@SuppressWarnings("unused") TMap node)
    {
        this.index = 26;
    }

    @Override
    public void caseTFlatten(@SuppressWarnings("unused") TFlatten node)
    {
        this.index = 27;
    }

    @Override
    public void caseTLength(@SuppressWarnings("unused") TLength node)
    {
        this.index = 28;
    }

    @Override
    public void caseTLambdaStart(@SuppressWarnings("unused") TLambdaStart node)
    {
        this.index = 29;
    }

    @Override
    public void caseTLambdaArrow(@SuppressWarnings("unused") TLambdaArrow node)
    {
        this.index = 30;
    }

    @Override
    public void caseTIdentity(@SuppressWarnings("unused") TIdentity node)
    {
        this.index = 31;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 32;
    }

    @Override
    public void caseTDef(@SuppressWarnings("unused") TDef node)
    {
        this.index = 33;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 34;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 35;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 36;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 37;
    }

    @Override
    public void caseTNotEqual(@SuppressWarnings("unused") TNotEqual node)
    {
        this.index = 38;
    }

    @Override
    public void caseTLte(@SuppressWarnings("unused") TLte node)
    {
        this.index = 39;
    }

    @Override
    public void caseTGte(@SuppressWarnings("unused") TGte node)
    {
        this.index = 40;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 41;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 42;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 43;
    }

    @Override
    public void caseTLogicalNot(@SuppressWarnings("unused") TLogicalNot node)
    {
        this.index = 44;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 45;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 46;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 47;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 48;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 49;
    }

    @Override
    public void caseTNeg(@SuppressWarnings("unused") TNeg node)
    {
        this.index = 50;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 51;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 52;
    }

    @Override
    public void caseTStartList(@SuppressWarnings("unused") TStartList node)
    {
        this.index = 53;
    }

    @Override
    public void caseTEndList(@SuppressWarnings("unused") TEndList node)
    {
        this.index = 54;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 55;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 56;
    }

    @Override
    public void caseTTernaryQuestionMark(@SuppressWarnings("unused") TTernaryQuestionMark node)
    {
        this.index = 57;
    }

    @Override
    public void caseTTernaryColon(@SuppressWarnings("unused") TTernaryColon node)
    {
        this.index = 58;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 59;
    }

    @Override
    public void caseTIntNumber(@SuppressWarnings("unused") TIntNumber node)
    {
        this.index = 60;
    }

    @Override
    public void caseTFloatNumber(@SuppressWarnings("unused") TFloatNumber node)
    {
        this.index = 61;
    }

    @Override
    public void caseTMisc(@SuppressWarnings("unused") TMisc node)
    {
        this.index = 62;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 63;
    }
}
