/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AAppendFuncName extends PFuncName
{
    private TAppend _append_;

    public AAppendFuncName()
    {
        // Constructor
    }

    public AAppendFuncName(
        @SuppressWarnings("hiding") TAppend _append_)
    {
        // Constructor
        setAppend(_append_);

    }

    @Override
    public Object clone()
    {
        return new AAppendFuncName(
            cloneNode(this._append_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppendFuncName(this);
    }

    public TAppend getAppend()
    {
        return this._append_;
    }

    public void setAppend(TAppend node)
    {
        if(this._append_ != null)
        {
            this._append_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._append_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._append_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._append_ == child)
        {
            this._append_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._append_ == oldChild)
        {
            setAppend((TAppend) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
