/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyString extends PString
{
    private TStringStart _stringStart_;
    private TStringEnd _stringEnd_;

    public AEmptyString()
    {
        // Constructor
    }

    public AEmptyString(
        @SuppressWarnings("hiding") TStringStart _stringStart_,
        @SuppressWarnings("hiding") TStringEnd _stringEnd_)
    {
        // Constructor
        setStringStart(_stringStart_);

        setStringEnd(_stringEnd_);

    }

    @Override
    public Object clone()
    {
        return new AEmptyString(
            cloneNode(this._stringStart_),
            cloneNode(this._stringEnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyString(this);
    }

    public TStringStart getStringStart()
    {
        return this._stringStart_;
    }

    public void setStringStart(TStringStart node)
    {
        if(this._stringStart_ != null)
        {
            this._stringStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringStart_ = node;
    }

    public TStringEnd getStringEnd()
    {
        return this._stringEnd_;
    }

    public void setStringEnd(TStringEnd node)
    {
        if(this._stringEnd_ != null)
        {
            this._stringEnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringEnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringStart_)
            + toString(this._stringEnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringStart_ == child)
        {
            this._stringStart_ = null;
            return;
        }

        if(this._stringEnd_ == child)
        {
            this._stringEnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringStart_ == oldChild)
        {
            setStringStart((TStringStart) newChild);
            return;
        }

        if(this._stringEnd_ == oldChild)
        {
            setStringEnd((TStringEnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
