/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AFormfeedEscapeChar extends PEscapeChar
{
    private TEscapeFormfeed _escapeFormfeed_;

    public AFormfeedEscapeChar()
    {
        // Constructor
    }

    public AFormfeedEscapeChar(
        @SuppressWarnings("hiding") TEscapeFormfeed _escapeFormfeed_)
    {
        // Constructor
        setEscapeFormfeed(_escapeFormfeed_);

    }

    @Override
    public Object clone()
    {
        return new AFormfeedEscapeChar(
            cloneNode(this._escapeFormfeed_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormfeedEscapeChar(this);
    }

    public TEscapeFormfeed getEscapeFormfeed()
    {
        return this._escapeFormfeed_;
    }

    public void setEscapeFormfeed(TEscapeFormfeed node)
    {
        if(this._escapeFormfeed_ != null)
        {
            this._escapeFormfeed_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeFormfeed_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeFormfeed_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeFormfeed_ == child)
        {
            this._escapeFormfeed_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeFormfeed_ == oldChild)
        {
            setEscapeFormfeed((TEscapeFormfeed) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
