/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseFunction extends PFunction
{
    private PBranch _branch_;

    public AIfElseFunction()
    {
        // Constructor
    }

    public AIfElseFunction(
        @SuppressWarnings("hiding") PBranch _branch_)
    {
        // Constructor
        setBranch(_branch_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseFunction(
            cloneNode(this._branch_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseFunction(this);
    }

    public PBranch getBranch()
    {
        return this._branch_;
    }

    public void setBranch(PBranch node)
    {
        if(this._branch_ != null)
        {
            this._branch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._branch_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._branch_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._branch_ == child)
        {
            this._branch_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._branch_ == oldChild)
        {
            setBranch((PBranch) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
