/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ALessEqualNativeBinOp extends PNativeBinOp
{
    private TLte _lte_;

    public ALessEqualNativeBinOp()
    {
        // Constructor
    }

    public ALessEqualNativeBinOp(
        @SuppressWarnings("hiding") TLte _lte_)
    {
        // Constructor
        setLte(_lte_);

    }

    @Override
    public Object clone()
    {
        return new ALessEqualNativeBinOp(
            cloneNode(this._lte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessEqualNativeBinOp(this);
    }

    public TLte getLte()
    {
        return this._lte_;
    }

    public void setLte(TLte node)
    {
        if(this._lte_ != null)
        {
            this._lte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lte_ == child)
        {
            this._lte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lte_ == oldChild)
        {
            setLte((TLte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
