/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AMapFunction extends PFunction
{
    private TMap _map_;
    private TLParen _lParen_;
    private PUnaryOp _unaryOp_;
    private TComma _comma_;
    private PListArgument _listArgument_;
    private TRParen _rParen_;

    public AMapFunction()
    {
        // Constructor
    }

    public AMapFunction(
        @SuppressWarnings("hiding") TMap _map_,
        @SuppressWarnings("hiding") TLParen _lParen_,
        @SuppressWarnings("hiding") PUnaryOp _unaryOp_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PListArgument _listArgument_,
        @SuppressWarnings("hiding") TRParen _rParen_)
    {
        // Constructor
        setMap(_map_);

        setLParen(_lParen_);

        setUnaryOp(_unaryOp_);

        setComma(_comma_);

        setListArgument(_listArgument_);

        setRParen(_rParen_);

    }

    @Override
    public Object clone()
    {
        return new AMapFunction(
            cloneNode(this._map_),
            cloneNode(this._lParen_),
            cloneNode(this._unaryOp_),
            cloneNode(this._comma_),
            cloneNode(this._listArgument_),
            cloneNode(this._rParen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMapFunction(this);
    }

    public TMap getMap()
    {
        return this._map_;
    }

    public void setMap(TMap node)
    {
        if(this._map_ != null)
        {
            this._map_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._map_ = node;
    }

    public TLParen getLParen()
    {
        return this._lParen_;
    }

    public void setLParen(TLParen node)
    {
        if(this._lParen_ != null)
        {
            this._lParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParen_ = node;
    }

    public PUnaryOp getUnaryOp()
    {
        return this._unaryOp_;
    }

    public void setUnaryOp(PUnaryOp node)
    {
        if(this._unaryOp_ != null)
        {
            this._unaryOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryOp_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PListArgument getListArgument()
    {
        return this._listArgument_;
    }

    public void setListArgument(PListArgument node)
    {
        if(this._listArgument_ != null)
        {
            this._listArgument_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listArgument_ = node;
    }

    public TRParen getRParen()
    {
        return this._rParen_;
    }

    public void setRParen(TRParen node)
    {
        if(this._rParen_ != null)
        {
            this._rParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._map_)
            + toString(this._lParen_)
            + toString(this._unaryOp_)
            + toString(this._comma_)
            + toString(this._listArgument_)
            + toString(this._rParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._map_ == child)
        {
            this._map_ = null;
            return;
        }

        if(this._lParen_ == child)
        {
            this._lParen_ = null;
            return;
        }

        if(this._unaryOp_ == child)
        {
            this._unaryOp_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._listArgument_ == child)
        {
            this._listArgument_ = null;
            return;
        }

        if(this._rParen_ == child)
        {
            this._rParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._map_ == oldChild)
        {
            setMap((TMap) newChild);
            return;
        }

        if(this._lParen_ == oldChild)
        {
            setLParen((TLParen) newChild);
            return;
        }

        if(this._unaryOp_ == oldChild)
        {
            setUnaryOp((PUnaryOp) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._listArgument_ == oldChild)
        {
            setListArgument((PListArgument) newChild);
            return;
        }

        if(this._rParen_ == oldChild)
        {
            setRParen((TRParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
