/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ANativeBinOp extends PBinOp
{
    private PNativeBinOp _nativeBinOp_;

    public ANativeBinOp()
    {
        // Constructor
    }

    public ANativeBinOp(
        @SuppressWarnings("hiding") PNativeBinOp _nativeBinOp_)
    {
        // Constructor
        setNativeBinOp(_nativeBinOp_);

    }

    @Override
    public Object clone()
    {
        return new ANativeBinOp(
            cloneNode(this._nativeBinOp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANativeBinOp(this);
    }

    public PNativeBinOp getNativeBinOp()
    {
        return this._nativeBinOp_;
    }

    public void setNativeBinOp(PNativeBinOp node)
    {
        if(this._nativeBinOp_ != null)
        {
            this._nativeBinOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nativeBinOp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nativeBinOp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nativeBinOp_ == child)
        {
            this._nativeBinOp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nativeBinOp_ == oldChild)
        {
            setNativeBinOp((PNativeBinOp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
