/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ANewlineEscapeChar extends PEscapeChar
{
    private TEscapeNewline _escapeNewline_;

    public ANewlineEscapeChar()
    {
        // Constructor
    }

    public ANewlineEscapeChar(
        @SuppressWarnings("hiding") TEscapeNewline _escapeNewline_)
    {
        // Constructor
        setEscapeNewline(_escapeNewline_);

    }

    @Override
    public Object clone()
    {
        return new ANewlineEscapeChar(
            cloneNode(this._escapeNewline_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewlineEscapeChar(this);
    }

    public TEscapeNewline getEscapeNewline()
    {
        return this._escapeNewline_;
    }

    public void setEscapeNewline(TEscapeNewline node)
    {
        if(this._escapeNewline_ != null)
        {
            this._escapeNewline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeNewline_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeNewline_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeNewline_ == child)
        {
            this._escapeNewline_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeNewline_ == oldChild)
        {
            setEscapeNewline((TEscapeNewline) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
