/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ASingleQuoteEscapeChar extends PEscapeChar
{
    private TEscapeSingleQuote _escapeSingleQuote_;

    public ASingleQuoteEscapeChar()
    {
        // Constructor
    }

    public ASingleQuoteEscapeChar(
        @SuppressWarnings("hiding") TEscapeSingleQuote _escapeSingleQuote_)
    {
        // Constructor
        setEscapeSingleQuote(_escapeSingleQuote_);

    }

    @Override
    public Object clone()
    {
        return new ASingleQuoteEscapeChar(
            cloneNode(this._escapeSingleQuote_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleQuoteEscapeChar(this);
    }

    public TEscapeSingleQuote getEscapeSingleQuote()
    {
        return this._escapeSingleQuote_;
    }

    public void setEscapeSingleQuote(TEscapeSingleQuote node)
    {
        if(this._escapeSingleQuote_ != null)
        {
            this._escapeSingleQuote_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeSingleQuote_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeSingleQuote_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeSingleQuote_ == child)
        {
            this._escapeSingleQuote_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeSingleQuote_ == oldChild)
        {
            setEscapeSingleQuote((TEscapeSingleQuote) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
