/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ATailNativeUnaryOp extends PNativeUnaryOp
{
    private TTail _tail_;

    public ATailNativeUnaryOp()
    {
        // Constructor
    }

    public ATailNativeUnaryOp(
        @SuppressWarnings("hiding") TTail _tail_)
    {
        // Constructor
        setTail(_tail_);

    }

    @Override
    public Object clone()
    {
        return new ATailNativeUnaryOp(
            cloneNode(this._tail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATailNativeUnaryOp(this);
    }

    public TTail getTail()
    {
        return this._tail_;
    }

    public void setTail(TTail node)
    {
        if(this._tail_ != null)
        {
            this._tail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tail_ == child)
        {
            this._tail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tail_ == oldChild)
        {
            setTail((TTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
