/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class AVerticalTabEscapeChar extends PEscapeChar
{
    private TEscapeVerticalTab _escapeVerticalTab_;

    public AVerticalTabEscapeChar()
    {
        // Constructor
    }

    public AVerticalTabEscapeChar(
        @SuppressWarnings("hiding") TEscapeVerticalTab _escapeVerticalTab_)
    {
        // Constructor
        setEscapeVerticalTab(_escapeVerticalTab_);

    }

    @Override
    public Object clone()
    {
        return new AVerticalTabEscapeChar(
            cloneNode(this._escapeVerticalTab_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVerticalTabEscapeChar(this);
    }

    public TEscapeVerticalTab getEscapeVerticalTab()
    {
        return this._escapeVerticalTab_;
    }

    public void setEscapeVerticalTab(TEscapeVerticalTab node)
    {
        if(this._escapeVerticalTab_ != null)
        {
            this._escapeVerticalTab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeVerticalTab_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeVerticalTab_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeVerticalTab_ == child)
        {
            this._escapeVerticalTab_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeVerticalTab_ == oldChild)
        {
            setEscapeVerticalTab((TEscapeVerticalTab) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
