/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class TEscapeBackspace extends Token
{
    public TEscapeBackspace()
    {
        super.setText("b");
    }

    public TEscapeBackspace(int line, int pos)
    {
        super.setText("b");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEscapeBackspace(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEscapeBackspace(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEscapeBackspace text.");
    }
}
