/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class TEscapeCarriageReturn extends Token
{
    public TEscapeCarriageReturn()
    {
        super.setText("r");
    }

    public TEscapeCarriageReturn(int line, int pos)
    {
        super.setText("r");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEscapeCarriageReturn(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEscapeCarriageReturn(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEscapeCarriageReturn text.");
    }
}
