/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class TEscapeFormfeed extends Token
{
    public TEscapeFormfeed()
    {
        super.setText("f");
    }

    public TEscapeFormfeed(int line, int pos)
    {
        super.setText("f");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEscapeFormfeed(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEscapeFormfeed(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEscapeFormfeed text.");
    }
}
