/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ADefsProgram extends PProgram
{
    private PDefList _defList_;
    private PFunc _func_;

    public ADefsProgram()
    {
        // Constructor
    }

    public ADefsProgram(
        @SuppressWarnings("hiding") PDefList _defList_,
        @SuppressWarnings("hiding") PFunc _func_)
    {
        // Constructor
        setDefList(_defList_);

        setFunc(_func_);

    }

    @Override
    public Object clone()
    {
        return new ADefsProgram(
            cloneNode(this._defList_),
            cloneNode(this._func_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefsProgram(this);
    }

    public PDefList getDefList()
    {
        return this._defList_;
    }

    public void setDefList(PDefList node)
    {
        if(this._defList_ != null)
        {
            this._defList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defList_ = node;
    }

    public PFunc getFunc()
    {
        return this._func_;
    }

    public void setFunc(PFunc node)
    {
        if(this._func_ != null)
        {
            this._func_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._func_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._defList_)
            + toString(this._func_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._defList_ == child)
        {
            this._defList_ = null;
            return;
        }

        if(this._func_ == child)
        {
            this._func_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._defList_ == oldChild)
        {
            setDefList((PDefList) newChild);
            return;
        }

        if(this._func_ == oldChild)
        {
            setFunc((PFunc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
