/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class ASlashEscapeChar extends PEscapeChar
{
    private TEscapeBackslash _escapeBackslash_;

    public ASlashEscapeChar()
    {
        // Constructor
    }

    public ASlashEscapeChar(
        @SuppressWarnings("hiding") TEscapeBackslash _escapeBackslash_)
    {
        // Constructor
        setEscapeBackslash(_escapeBackslash_);

    }

    @Override
    public Object clone()
    {
        return new ASlashEscapeChar(
            cloneNode(this._escapeBackslash_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASlashEscapeChar(this);
    }

    public TEscapeBackslash getEscapeBackslash()
    {
        return this._escapeBackslash_;
    }

    public void setEscapeBackslash(TEscapeBackslash node)
    {
        if(this._escapeBackslash_ != null)
        {
            this._escapeBackslash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escapeBackslash_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escapeBackslash_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escapeBackslash_ == child)
        {
            this._escapeBackslash_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escapeBackslash_ == oldChild)
        {
            setEscapeBackslash((TEscapeBackslash) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
