/* This file was generated by SableCC (http://www.sablecc.org/). */

package wolf.node;

import wolf.analysis.*;

@SuppressWarnings("nls")
public final class THead extends Token
{
    public THead()
    {
        super.setText("h");
    }

    public THead(int line, int pos)
    {
        super.setText("h");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THead(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHead(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THead text.");
    }
}
