/* This file was generated by SableCC (http://www.sablecc.org/). */

package three_point_one.analysis;

import three_point_one.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseACompoundS(ACompoundS node);
    void caseAAssignS(AAssignS node);
    void caseAPrintS(APrintS node);
    void caseAAssignC(AAssignC node);
    void caseAPrintC(APrintC node);
    void caseAAssignStmt(AAssignStmt node);
    void caseAPrintStmt(APrintStmt node);
    void caseAIdE(AIdE node);
    void caseANumE(ANumE node);
    void caseAAddE(AAddE node);
    void caseAESeqE(AESeqE node);
    void caseAIdTerm(AIdTerm node);
    void caseANumTerm(ANumTerm node);
    void caseAESeqTerm(AESeqTerm node);
    void caseAESeq(AESeq node);
    void caseAEL(AEL node);
    void caseALSeqL(ALSeqL node);

    void caseTPrint(TPrint node);
    void caseTSpace(TSpace node);
    void caseTPlus(TPlus node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTAssign(TAssign node);
    void caseTSemi(TSemi node);
    void caseTComma(TComma node);
    void caseTId(TId node);
    void caseTNum(TNum node);
    void caseTMisc(TMisc node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
